package util

const TAG_USER  = "USR"
const TAG_ADDRESS  = "ADD"
const TAG_BUSANA  = "BSN"
const TAG_TRANSAKSI = "TRX"
const TAG_REKENING = "REK"
const TAG_RATING = "RAT"

const TAG_USER_TBL = "tb_user"
const TAG_ADDRESS_TBL = "tb_alamat"
const TAG_BUSANA_TBL = "tb_busana"
const TAG_KATEGORI_TBL = "tb_kategori"
const TAG_GENDER_TBL = "tb_gender"
const TAG_REKENING_TBL = "tb_rekening"
const TAG_TRANSAKSI_TBL = "tb_transaksi"
const TAG_TRANSAKSIDETAIL_TBL = "tb_transaksi_detail"
const TAG_PENGIRIMAN_TBL = "tb_pengiriman"
const TAG_PENGIRIMANBUSANA_TBL = "tb_pengiriman_busana"
const TAG_STATUS_TBL = "tb_status"
const TAG_RATING_TBL = "tb_rating"
const TAG_RATINGSUMMARY_TBL = "tb_rating_summary"
const TAG_PENGUNJUNG_TBL = "tb_pengunjung"

const TAG_USER_PK = "id_user"
const TAG_ADDRESS_PK = "id_alamat"
const TAG_BUSANA_PK = "id_busana"
const TAG_KATEGORI_PK = "id_kategori"
const TAG_GENDER_PK = "id_gender"
const TAG_REKENING_PK = "id_rekening"
const TAG_TRANSAKSI_PK = "id_transaksi"
const TAG_PENGIRIMAN_PK = "id_pengiriman"
const TAG_STATUS_PK = "id_status"
const TAG_RATING_PK = "id_rating"

//ID status
const STS_FASHION_NEW_01 = "STS01"
const STS_FASHION_RENT_02 = "STS02"
const STS_TRX_CONFIRM_RENT_01 = "STS11"
const STS_TRX_REJECT_OWNER_02 = "STS12"
const STS_TRX_APPROVE_OWNER_03 = "STS13"
const STS_TRX_CONFIRMATIONPAYMENT_OWNER_04 = "STS14"
const STS_TRX_ALREADYPAID_RENT_05 = "STS15"
const STS_TRX_WAITTOSHIPPMENT_OWNER_06 = "STS16"
const STS_TRX_SHIPPED_OWNER_07 = "STS17"
const STS_TRX_RECEIVE_RENT_08 = "STS18"
const STS_TRX_RETRIVE_RENT_09 = "STS19"
const STS_TRX_RATING_BOTH_10 = "STS20"
const STS_TRX_RATING_RENT_11 = "STS21"
const STS_TRX_RATING_OWNER_12 = "STS22"
const STS_TRX_FINISHED_BOTH_13 = "STS23"